export { createDesktopBridge } from "./client";
export { createFakeDesktopBridge, fakeError } from "./fake-bridge";
export type { FakeBridgeOptions } from "./fake-bridge";
export { pickDirectory } from "./folder-picker";
export { pickImages } from "./image-picker";
export { subscribeImageDrops } from "./image-drop";
export type { ImageDropEvent } from "./image-drop";
export type {
  DesktopBridge,
  DesktopCommand,
  DesktopEvent,
  TypedDesktopEvent,
  DesktopResult,
  BootstrapSnapshot,
  BootstrapStatus,
  Unsubscribe,
  AppError,
  TaskId,
  SessionId,
  ProjectId,
  CorrelationId,
  RuntimeLoginPayload,
  ProjectOpenPayload,
  ProjectForgetPayload,
  TaskCreatePayload,
  TaskOpenPayload,
  TaskArchivePayload,
  TurnSendPayload,
  TurnCancelPayload,
  SessionConfigurePayload,
  SessionResumePayload,
  PermissionResolvePayload,
  PlanResolvePayload,
  ArtifactImportPayload,
  ArtifactDescriptor,
  ArtifactImportResult,
  ArtifactSavePayload,
  WorkspaceInspectPayload,
  WorktreeAdoptPayload,
  ReviewDiffPayload,
  ReviewCheckpointPayload,
  IntegrationPreflightPayload,
  IntegrationExecutePayload,
  WorktreeCleanupPayload,
  RecoveryRestorePayload,
  RecoveryDeletePayload,
  SessionEvent,
  RuntimeUpdatedPayload,
  TaskSnapshotPayload,
  TaskStatePayload,
  MessageDeltaPayload,
  ActivityUpdatedPayload,
  PermissionRequestedPayload,
  PermissionOperationView,
  PermissionOption,
  PlanUpdatedPayload,
  ChangesUpdatedPayload,
  ArtifactAvailablePayload,
  ResourceWarningPayload,
  DiagnosticNoticePayload,
} from "./types";
export { EventTypes, ErrorCodes } from "./types";
